services:
  server:
    image: 011528257712.dkr.ecr.us-east-1.amazonaws.com/meddiflux-eb:${TAG}
    ports:
      - 80:8080
    environment:
      DB_USER: postgres
      DB_PWD: postgres
      DB_HOST: database
      DB_PORT: 5432