services:
  server:
    env_file: .env
    container_name: meddiflux
    image: 011528257712.dkr.ecr.us-east-1.amazonaws.com/meddiflux-eb:latest
    ports:
      - mode: ingress
        target: 8080
        published: "80"
        protocol: tcp


# services:
#   server:
#     env_file: .env
#     image: 864981753284.dkr.ecr.us-east-1.amazonaws.com/meddiflux:latest
#     ports:
#       - mode: ingress
#         target: 8080
#         published: "80"
#         protocol: tcp