AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  DBCluster

  Sample SAM Template for DBCluster
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  LigarDBCluster:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:      
      Handler: src/handlers/dbcluster-automate.startDBCluster
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      Events:
        CloudWatchEvent:
          Type: Schedule # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Schedule: cron(29, 16 ?, * MON-FRI *)
      Policies:
        - Statement:
          - Sid: IniciarRDS
            Effect: Allow
            Action:
              - rds:StartDBCluster
            Resource: '*'
  DesligarDBCluster:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:      
      Handler: src/handlers/dbcluster-automate.stopDBCluster
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      Events:
        CloudWatchEvent:
          Type: Schedule # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Schedule: cron(38, 16 ?, * MON-FRI *)
      Policies:
        - Statement:
          - Sid: PararRDS
            Effect: Allow
            Action:
              - rds:StopDBCluster
            Resource: '*'